package cn.maolin.myblog.entity;

import lombok.Data;

import java.io.Serializable;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_comments
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Comments implements Serializable {
    /**
     * Database Column Remarks:
     * 主键
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.coid
     *
     * @mbg.generated
     */
    private Integer coid;

    /**
     * Database Column Remarks:
     * 回复文章
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     * Database Column Remarks:
     * 创建日期
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.created
     *
     * @mbg.generated
     */
    private Integer created;

    /**
     * Database Column Remarks:
     * 作者
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     * Database Column Remarks:
     * 作者ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.author_id
     *
     * @mbg.generated
     */
    private Integer authorId;

    /**
     * Database Column Remarks:
     * 拥有着ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.owner_id
     *
     * @mbg.generated
     */
    private Integer ownerId;

    /**
     * Database Column Remarks:
     * 邮箱
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.mail
     *
     * @mbg.generated
     */
    private String mail;

    /**
     * Database Column Remarks:
     * 链接
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     * ip地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * Database Column Remarks:
     * 代理
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.agent
     *
     * @mbg.generated
     */
    private String agent;

    /**
     * Database Column Remarks:
     * 类型
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     * 状态
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     * 上级
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.parent
     *
     * @mbg.generated
     */
    private Integer parent;

    /**
     * Database Column Remarks:
     * 内容
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_comments.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_comments
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

}