package cn.maolin.myblog.entity;

import lombok.Data;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_logs
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Logs implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   产生的动作
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.action
     *
     * @mbg.generated
     */
    private String action;

    /**
     * Database Column Remarks:
     *   产生的数据
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.data
     *
     * @mbg.generated
     */
    private String data;

    /**
     * Database Column Remarks:
     *   产生的id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.author_id
     *
     * @mbg.generated
     */
    private Integer authorId;

    /**
     * Database Column Remarks:
     *   ip地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.ip
     *
     * @mbg.generated
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   记录日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_logs.created
     *
     * @mbg.generated
     */
    private Integer created;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_logs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

}