package cn.maolin.myblog.entity;

import lombok.Data;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_metas
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Metas implements Serializable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     * Database Column Remarks:
     *   分类名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   分类缩写
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.slug
     *
     * @mbg.generated
     */
    private String slug;

    /**
     * Database Column Remarks:
     *   分类类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.type
     *
     * @mbg.generated
     */
    private String type;

    /**
     * Database Column Remarks:
     *   描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.sort
     *
     * @mbg.generated
     */
    private Byte sort;

    /**
     * Database Column Remarks:
     *   上级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_metas.parent
     *
     * @mbg.generated
     */
    private Integer parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_metas
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * 文章数
     */
    private Integer count;
}