package cn.maolin.myblog.entity;

import lombok.Data;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_options
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Options implements Serializable {
    /**
     * Database Column Remarks:
     *   配置名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_options.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   配置描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_options.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   配置值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_options.value
     *
     * @mbg.generated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_options
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

}