package cn.maolin.myblog.entity;

import lombok.Data;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_relationships
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class Relationships implements Serializable {
    /**
     * Database Column Remarks:
     *   内容主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationships.cid
     *
     * @mbg.generated
     */
    private Integer cid;

    /**
     * Database Column Remarks:
     *   项目主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_relationships.mid
     *
     * @mbg.generated
     */
    private Integer mid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_relationships
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}